
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Bootstrap_Series2_development

test:
  <<: *default
  database: Bootstrap_Series2_test

production:
  <<: *default
  database: Bootstrap_Series2_production
  username: Bootstrap_Series2
  password: <%= ENV['BOOTSTRAP_SERIES2_DATABASE_PASSWORD'] %>
